# Generated by Django 6.1.1 on 2026-10-01 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('never', 'Never married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='never', max_length=10)),
                ('sect', models.CharField(choices=[('sunni', 'Sunni'), ('shia', 'Shia'), ('other', 'Other')], default='sunni', max_length=10)),
                ('prayer', models.CharField(choices=[('regular', 'Prays regularly'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], default='regular', max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('looking_for', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='matches.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='matches.profile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
